service: warriorbeatapi
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-s3-local
custom:
  tableName: 'feed-table-${self:provider.stage}'
  wsgi:
    app: warriorbeat.__init__.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  dynamodb:
    start:
      migrate: true
  s3:
    host: 0.0.0.0
    port: 9000
    directory: ./.s3-local
    cors: false

package:
  exclude:
    - node_modules/**
    - venv/**
app: warriorbeatapi
tenant: bradenm
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  apiName: wbapi
  stackName: WarriorBeat-Serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { 'Fn::GetAtt': ['FeedDynamoTable', 'Arn'] }
  environment:
    FEED_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    FeedDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: feedId
            AttributeType: S
        KeySchema:
          - AttributeName: feedId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    FeedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: feed-bucket
